FROM python:3.9.1

# Create a group and user to run our app
ARG APP_USER=anychat
ARG WORKON_HOME
ARG PIPENV_CACHE_DIR
ENV HOME /home/anychat

RUN groupadd -r ${APP_USER} && useradd --no-log-init -r -g ${APP_USER} ${APP_USER}

# Install packages needed to run your application (not build deps):
#   libpcre2 -- This is a library of functions to support regular expressions whose syntax and semantics are as close as possible to those of the Perl 5 language.
#   mime-support -- for mime types when serving static files
#   libmagic1 -- required by python-magic for mime detection
#   default-libmysqlclient-dev -- for mysql database support
#   inkscape -- for exporting vector graphics like pdf, eps, ps
#   libcurl4-nss-dev libssl-dev -- for pycurl installation (used by celery[sqs])
# We need to recreate the /usr/share/man/man{1..8} directories first because
# they were clobbered by a parent image.
RUN set -ex \
    && RUN_DEPS=" \
    libpcre3 \
    mime-support \
    libmagic1 \
    default-libmysqlclient-dev \
    inkscape \
    libcurl4-nss-dev libssl-dev \
    " \
    && seq 1 8 | xargs -I{} mkdir -p /usr/share/man/man{} \
    && apt-get update && apt-get install -y --no-install-recommends $RUN_DEPS \
    && pip install pipenv \
    # Create directories
    && mkdir /app/ \
    && mkdir ${WORKON_HOME} \
    && mkdir ${PIPENV_CACHE_DIR} \
    && mkdir /app/config/ \
    && mkdir /app/scripts/ \
    && mkdir -p /static_cdn/static_root/ \
    && chown -R ${APP_USER} /static_cdn/

RUN chown -R ${APP_USER} /home/anychat
RUN chown -R ${APP_USER} ${WORKON_HOME}
RUN chown -R ${APP_USER} ${PIPENV_CACHE_DIR}

WORKDIR /app/

COPY Pipfile Pipfile.lock /app/

RUN set -ex \
    && BUILD_DEPS=" \
    build-essential \
    libpcre3-dev \
    libpq-dev \
    vim \
    " \
    && apt-get update && apt-get install -y --no-install-recommends $BUILD_DEPS \
    && pipenv install --deploy --system

# Copy your application app to the container (make sure you create a .dockerignore file if any large files or directories should be excluded)
COPY ./src /app/
COPY scripts/ /app/scripts/
COPY configs/ /app/configs/
COPY library_data /library_data

# uWSGI will listen on this port
EXPOSE 8000

## Add any static environment variables needed by Django or your settings file here:
#ENV DJANGO_SETTINGS_MODULE=my_project.settings.deploy
#
## Call collectstatic (customize the following line with the minimal environment variables needed for manage.py to run):
#RUN DATABASE_URL='' python manage.py collectstatic --noinput
#
## Tell uWSGI where to find your wsgi file (change this):
ENV UWSGI_WSGI_FILE=qcg/wsgi.py

# Base uWSGI configuration (you shouldn't need to change these):
ENV UWSGI_HTTP=:8000 UWSGI_MASTER=1 UWSGI_HTTP_AUTO_CHUNKED=1 UWSGI_HTTP_KEEPALIVE=1 UWSGI_LAZY_APPS=1 UWSGI_WSGI_ENV_BEHAVIOR=holy

# Number of uWSGI workers and threads per worker (customize as needed):
ENV UWSGI_WORKERS=2 UWSGI_THREADS=4

# uWSGI static file serving configuration (customize or comment out if not needed):
ENV UWSGI_STATIC_MAP="/static/=/static_cdn/static_root/" UWSGI_STATIC_EXPIRES_URI="/static/.*\.[a-f0-9]{12,}\.(css|js|png|jpg|jpeg|gif|ico|woff|ttf|otf|svg|scss|map|txt) 315360000"

# Deny invalid hosts before they get to Django (uncomment and change to your hostname(s)):
# ENV UWSGI_ROUTE_HOST="^(?!localhost:8000$) break:400"

# Change to a non-root user
USER ${APP_USER}:${APP_USER}

# Uncomment after creating your docker-entrypoint.sh
ENTRYPOINT ["/app/scripts/docker/entrypoint.sh"]

# Start uWSGI
#CMD ["uwsgi", "--show-config"]
